"""
test_robustness.py
==================
Test suite for subprojects/09_robustness/run_robustness.py

Run from the Paper_GFJ directory:
    python -m pytest subprojects/09_robustness/test_robustness.py -v

Expected: all tests pass (outputs generated by run_robustness.py).
"""

import json
import os
import unittest

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
RESULTS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "results", "robustness"
)


def _path(filename: str) -> str:
    return os.path.join(RESULTS_DIR, filename)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _load_summary() -> pd.DataFrame:
    return pd.read_csv(_path("robustness_summary.csv"))


def _load_theta() -> pd.DataFrame:
    return pd.read_csv(_path("state_lp_theta.csv"))


def _load_manifest() -> dict:
    with open(_path("manifest.json")) as f:
        return json.load(f)


def _summary_k0(check_id: str, outcome: str = "EMFI") -> pd.Series | None:
    df = _load_summary()
    sub = df[(df["check_id"] == check_id) & (df["outcome"] == outcome) & (df["horizon"] == 0)]
    return sub.iloc[0] if not sub.empty else None


def _theta_k0(check_id: str) -> float | None:
    df = _load_theta()
    sub = df[(df["check_id"] == check_id) & (df["horizon"] == 0) & df["theta"].notna()]
    return float(sub["theta"].iloc[0]) if not sub.empty else None


# ===========================================================================
# 1. Output files
# ===========================================================================
class TestOutputFiles(unittest.TestCase):
    REQUIRED = [
        "robustness_summary.csv",
        "state_lp_theta.csv",
        "Fig_Robustness_LP.png",
        "Fig_Robustness_StateLPTheta.png",
        "manifest.json",
    ]

    def test_all_files_exist(self):
        missing = [f for f in self.REQUIRED if not os.path.isfile(_path(f))]
        self.assertEqual(missing, [], msg=f"Missing output files: {missing}")

    def test_all_files_nonempty(self):
        empty = [f for f in self.REQUIRED
                 if os.path.isfile(_path(f)) and os.path.getsize(_path(f)) == 0]
        self.assertEqual(empty, [], msg=f"Empty output files: {empty}")


# ===========================================================================
# 2. Summary CSV structure
# ===========================================================================
class TestSummaryStructure(unittest.TestCase):
    REQUIRED_COLS = ["check_id", "check_name", "outcome", "shock",
                     "horizon", "beta", "se", "ci95_lo", "ci95_hi", "nobs"]

    @classmethod
    def setUpClass(cls):
        cls.df = _load_summary()

    def test_required_columns(self):
        missing = [c for c in self.REQUIRED_COLS if c not in self.df.columns]
        self.assertEqual(missing, [], msg=f"Missing columns: {missing}")

    def test_at_least_10_checks(self):
        n = self.df["check_id"].nunique()
        self.assertGreaterEqual(n, 10, msg=f"Expected ≥10 checks, got {n}")

    def test_baseline_present(self):
        self.assertIn("R00", self.df["check_id"].values,
                      msg="Baseline (R00) missing from summary")

    def test_key_checks_present(self):
        for check in ["R01", "R02", "R08", "R09"]:
            self.assertIn(check, self.df["check_id"].values,
                          msg=f"Check {check} missing from summary")

    def test_key_horizons_covered(self):
        for k in [0, 1, 5, 10, 20]:
            has_k = (self.df["horizon"] == k).any()
            self.assertTrue(has_k, msg=f"Horizon k={k} not present in summary")

    def test_no_nan_in_baseline_betas(self):
        base = self.df[self.df["check_id"] == "R00"]
        nan_count = base["beta"].isna().sum()
        self.assertEqual(nan_count, 0, msg=f"Baseline has {nan_count} NaN betas")


# ===========================================================================
# 3. State LP theta structure
# ===========================================================================
class TestThetaStructure(unittest.TestCase):
    REQUIRED_COLS = ["check_id", "check_name", "outcome", "horizon", "theta"]

    @classmethod
    def setUpClass(cls):
        cls.df = _load_theta()

    def test_required_columns(self):
        missing = [c for c in self.REQUIRED_COLS if c not in self.df.columns]
        self.assertEqual(missing, [], msg=f"Missing theta columns: {missing}")

    def test_emfi_substitution_checks_present(self):
        for check in ["R03", "R04", "R05"]:
            self.assertIn(check, self.df["check_id"].values,
                          msg=f"EMFI substitution check {check} missing from theta CSV")

    def test_has_k0_entries(self):
        k0 = self.df[self.df["horizon"] == 0]
        self.assertGreater(len(k0), 0, msg="No k=0 entries in theta CSV")


# ===========================================================================
# 4. Baseline LP result
# ===========================================================================
class TestBaselineLP(unittest.TestCase):
    def test_baseline_beta_k0_positive(self):
        row = _summary_k0("R00", "EMFI")
        self.assertIsNotNone(row, msg="Baseline R00 EMFI k=0 not found")
        self.assertGreater(float(row["beta"]), 0,
                           msg=f"Baseline β_k0 should be positive, got {row['beta']:.4f}")

    def test_baseline_beta_k0_magnitude(self):
        """β_k0 should be in the range (0.1, 2.0) — consistent with Phase 6."""
        row = _summary_k0("R00", "EMFI")
        self.assertIsNotNone(row)
        beta = float(row["beta"])
        self.assertGreater(beta, 0.1, msg=f"β_k0 = {beta:.4f} seems too small")
        self.assertLess(beta, 2.0,   msg=f"β_k0 = {beta:.4f} seems too large")

    def test_baseline_nobs(self):
        row = _summary_k0("R00", "EMFI")
        self.assertIsNotNone(row)
        n = int(row["nobs"])
        self.assertGreater(n, 2000, msg=f"Baseline nobs should be >2000, got {n}")

    def test_baseline_beta_k1_positive(self):
        df = _load_summary()
        r = df[(df["check_id"] == "R00") & (df["outcome"] == "EMFI") & (df["horizon"] == 1)]
        self.assertFalse(r.empty, msg="Baseline k=1 not found")
        self.assertGreater(float(r["beta"].iloc[0]), 0,
                           msg="Baseline β_k1 should be positive")


# ===========================================================================
# 5. COVID exclusion (R01)
# ===========================================================================
class TestCOVIDExclusion(unittest.TestCase):
    def test_covid_beta_k0_positive(self):
        row = _summary_k0("R01", "EMFI")
        self.assertIsNotNone(row, msg="COVID exclusion R01 EMFI k=0 not found")
        self.assertGreater(float(row["beta"]), 0,
                           msg=f"COVID excl β_k0 should be positive, got {row['beta']:.4f}")

    def test_covid_nobs_reduced(self):
        """COVID exclusion should reduce sample by ~150–300 trading days."""
        row_base = _summary_k0("R00", "EMFI")
        row_covid = _summary_k0("R01", "EMFI")
        self.assertIsNotNone(row_base)
        self.assertIsNotNone(row_covid)
        reduction = int(row_base["nobs"]) - int(row_covid["nobs"])
        self.assertGreater(reduction, 100, msg=f"COVID excl reduction = {reduction} (expected >100)")
        self.assertLess(reduction, 400,    msg=f"COVID excl reduction = {reduction} (expected <400)")

    def test_covid_pstress_present(self):
        df = _load_summary()
        sub = df[(df["check_id"] == "R01") & (df["outcome"] == "P_stress") & (df["horizon"] == 0)]
        self.assertFalse(sub.empty, msg="COVID excl P_stress k=0 not found")

    def test_covid_tci_present(self):
        df = _load_summary()
        sub = df[(df["check_id"] == "R01") & (df["outcome"] == "tci_w100") & (df["horizon"] == 0)]
        self.assertFalse(sub.empty, msg="COVID excl tci_w100 k=0 not found")

    def test_covid_beta_magnitude_vs_baseline(self):
        """COVID excl β should be somewhat smaller than baseline but same sign."""
        row_base  = _summary_k0("R00", "EMFI")
        row_covid = _summary_k0("R01", "EMFI")
        self.assertIsNotNone(row_base)
        self.assertIsNotNone(row_covid)
        # COVID beta should be positive and less than 2x the baseline
        ratio = float(row_covid["beta"]) / float(row_base["beta"])
        self.assertGreater(ratio, 0,   msg="COVID excl beta should be positive")
        self.assertLess(ratio, 2.0,    msg=f"COVID excl beta ratio={ratio:.2f} vs baseline (unexpected)")


# ===========================================================================
# 6. Ukraine exclusion (R02)
# ===========================================================================
class TestUkraineExclusion(unittest.TestCase):
    def test_ukraine_beta_k0_positive(self):
        """Ukraine excl β_k0 should remain positive (other shocks still active)."""
        row = _summary_k0("R02", "EMFI")
        self.assertIsNotNone(row, msg="Ukraine excl R02 EMFI k=0 not found")
        self.assertGreater(float(row["beta"]), 0,
                           msg=f"Ukraine excl β_k0 should be positive, got {row['beta']:.4f}")

    def test_ukraine_nobs_reduced(self):
        row_base = _summary_k0("R00", "EMFI")
        row_ukr  = _summary_k0("R02", "EMFI")
        self.assertIsNotNone(row_base)
        self.assertIsNotNone(row_ukr)
        reduction = int(row_base["nobs"]) - int(row_ukr["nobs"])
        self.assertGreater(reduction, 50,  msg=f"Ukraine excl reduction = {reduction} too small")
        self.assertLess(reduction, 300,    msg=f"Ukraine excl reduction = {reduction} too large")


# ===========================================================================
# 7. Placebo test (R08)
# ===========================================================================
class TestPlacebo(unittest.TestCase):
    def test_placebo_beta_k0_near_zero_or_negative(self):
        """Future-shock placebo β_k0 must be ≤ 0 or very small (no spurious prediction)."""
        row = _summary_k0("R08", "EMFI")
        self.assertIsNotNone(row, msg="Placebo R08 EMFI k=0 not found")
        beta = float(row["beta"])
        self.assertLess(beta, 0.15,
                        msg=f"Placebo β_k0 = {beta:.4f} should be ≤ 0.15 (no spurious fwd prediction)")

    def test_placebo_beta_smaller_than_baseline(self):
        row_base    = _summary_k0("R00", "EMFI")
        row_placebo = _summary_k0("R08", "EMFI")
        self.assertIsNotNone(row_base)
        self.assertIsNotNone(row_placebo)
        self.assertLess(float(row_placebo["beta"]), float(row_base["beta"]),
                        msg="Placebo β_k0 should be < baseline β_k0")


# ===========================================================================
# 8. Alternative shock aggregation (R09, R10)
# ===========================================================================
class TestAltShock(unittest.TestCase):
    def test_avgshock_beta_k0_positive(self):
        row = _summary_k0("R09", "EMFI")
        self.assertIsNotNone(row, msg="AvgShock R09 EMFI k=0 not found")
        self.assertGreater(float(row["beta"]), 0,
                           msg=f"AvgShock β_k0 should be positive, got {row['beta']:.4f}")

    def test_breadthshock_beta_k0_positive(self):
        row = _summary_k0("R10", "EMFI")
        self.assertIsNotNone(row, msg="BreadthShock R10 EMFI k=0 not found")
        self.assertGreater(float(row["beta"]), 0,
                           msg=f"BreadthShock β_k0 should be positive, got {row['beta']:.4f}")


# ===========================================================================
# 9. EMFI construction robustness (R03, R04, R05, R11, R12)
# ===========================================================================
class TestEMFIConstruction(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.df = _load_summary()

    def _beta_k0(self, check_id: str, outcome: str) -> float | None:
        sub = self.df[(self.df["check_id"] == check_id) &
                      (self.df["outcome"] == outcome) &
                      (self.df["horizon"] == 0)]
        return float(sub["beta"].iloc[0]) if not sub.empty else None

    def test_emfi3comp_beta_k0_positive(self):
        beta = self._beta_k0("R03", "EMFI_3comp")
        self.assertIsNotNone(beta, msg="R03 EMFI_3comp k=0 not found")
        self.assertGreater(beta, 0, msg=f"R03 β_k0 = {beta:.4f} should be positive")

    def test_acuteemfi_beta_k0_positive(self):
        beta = self._beta_k0("R04", "AcuteEMFI")
        self.assertIsNotNone(beta, msg="R04 AcuteEMFI k=0 not found")
        self.assertGreater(beta, 0, msg=f"R04 β_k0 = {beta:.4f} should be positive")

    def test_eqwtemfi_beta_k0_positive(self):
        beta = self._beta_k0("R05", "EqWtEMFI")
        self.assertIsNotNone(beta, msg="R05 EqWtEMFI k=0 not found")
        self.assertGreater(beta, 0, msg=f"R05 β_k0 = {beta:.4f} should be positive")

    def test_tci60_beta_k0_positive_if_present(self):
        beta = self._beta_k0("R11", "EMFI_tci60")
        if beta is None:
            self.skipTest("R11 (TCI W=60) not available — tci_w60 missing")
        self.assertGreater(beta, 0, msg=f"R11 β_k0 = {beta:.4f} should be positive")

    def test_tci150_beta_k0_positive_if_present(self):
        beta = self._beta_k0("R12", "EMFI_tci150")
        if beta is None:
            self.skipTest("R12 (TCI W=150) not available — tci_w150 missing")
        self.assertGreater(beta, 0, msg=f"R12 β_k0 = {beta:.4f} should be positive")


# ===========================================================================
# 10. State LP amplification (θ_k0)
# ===========================================================================
class TestStateLPTheta(unittest.TestCase):
    def test_emfi3comp_theta_positive(self):
        theta = _theta_k0("R03")
        self.assertIsNotNone(theta, msg="R03 theta_k0 not found")
        self.assertGreater(theta, 0,
                           msg=f"R03 (EMFI_3comp) θ_k0 should be positive, got {theta:.4f}")

    def test_acuteemfi_theta_positive(self):
        theta = _theta_k0("R04")
        self.assertIsNotNone(theta, msg="R04 theta_k0 not found")
        self.assertGreater(theta, 0,
                           msg=f"R04 (AcuteEMFI) θ_k0 should be positive, got {theta:.4f}")

    def test_eqwtemfi_theta_positive(self):
        theta = _theta_k0("R05")
        self.assertIsNotNone(theta, msg="R05 theta_k0 not found")
        self.assertGreater(theta, 0,
                           msg=f"R05 (EqualWeight EMFI) θ_k0 should be positive, got {theta:.4f}")

    def test_tci60_theta_positive_if_present(self):
        theta = _theta_k0("R11")
        if theta is None:
            self.skipTest("R11 not available")
        self.assertGreater(theta, 0,
                           msg=f"R11 (TCI W=60) θ_k0 should be positive, got {theta:.4f}")

    def test_tci150_theta_positive_if_present(self):
        theta = _theta_k0("R12")
        if theta is None:
            self.skipTest("R12 not available")
        self.assertGreater(theta, 0,
                           msg=f"R12 (TCI W=150) θ_k0 should be positive, got {theta:.4f}")

    def test_theta_magnitude_reasonable(self):
        """All EMFI-construction θ_k0 values should be in (0, 5) — reasonable range."""
        for check_id in ["R03", "R04", "R05"]:
            theta = _theta_k0(check_id)
            if theta is None:
                continue
            self.assertGreater(theta, 0, msg=f"{check_id} θ_k0 should be > 0")
            self.assertLess(theta, 5.0,  msg=f"{check_id} θ_k0 = {theta:.3f} seems implausibly large")

    def test_hf_p66_theta_present(self):
        """HF p66 binary check should have a theta entry."""
        df = _load_theta()
        sub = df[(df["check_id"] == "R06") & (df["horizon"] == 0)]
        self.assertFalse(sub.empty, msg="R06 (HF p66) theta k=0 not found")

    def test_hf_p66_theta_positive(self):
        df = _load_theta()
        sub = df[(df["check_id"] == "R06") & (df["horizon"] == 0) & df["theta"].notna()]
        if sub.empty:
            self.skipTest("R06 theta is NaN")
        theta = float(sub["theta"].iloc[0])
        self.assertGreater(theta, 0,
                           msg=f"R06 (HF p66) θ_k0 should be positive, got {theta:.4f}")


# ===========================================================================
# 11. IRF sign consistency across horizons
# ===========================================================================
class TestIRFConsistency(unittest.TestCase):
    """Baseline and key checks should show positive β at short horizons (k=0,1)."""

    @classmethod
    def setUpClass(cls):
        cls.df = _load_summary()

    def _beta_at(self, check_id, outcome, horizon):
        sub = self.df[(self.df["check_id"] == check_id) &
                      (self.df["outcome"] == outcome) &
                      (self.df["horizon"] == horizon)]
        return float(sub["beta"].iloc[0]) if not sub.empty else None

    def test_baseline_positive_k0_k1(self):
        for k in [0, 1]:
            beta = self._beta_at("R00", "EMFI", k)
            self.assertIsNotNone(beta, msg=f"Baseline k={k} not found")
            self.assertGreater(beta, 0, msg=f"Baseline β at k={k} should be positive, got {beta:.4f}")

    def test_covid_excl_positive_k0_k1(self):
        for k in [0, 1]:
            beta = self._beta_at("R01", "EMFI", k)
            self.assertIsNotNone(beta, msg=f"COVID excl k={k} not found")
            self.assertGreater(beta, 0, msg=f"COVID excl β at k={k} should be positive, got {beta:.4f}")

    def test_placebo_not_positive_at_k0(self):
        beta = self._beta_at("R08", "EMFI", 0)
        self.assertIsNotNone(beta, msg="Placebo k=0 not found")
        self.assertLess(beta, 0.15,
                        msg=f"Placebo β_k0 = {beta:.4f} — should not be meaningfully positive")


# ===========================================================================
# 12. Manifest
# ===========================================================================
class TestManifest(unittest.TestCase):
    REQUIRED_KEYS = [
        "generated_at", "script", "n_checks", "n_obs_baseline", "n_obs_covid_excl",
        "baseline_beta_k0", "covid_beta_k0", "placebo_beta_k0",
        "theta_k0_by_check", "outputs",
    ]

    @classmethod
    def setUpClass(cls):
        cls.m = _load_manifest()

    def test_required_keys(self):
        missing = [k for k in self.REQUIRED_KEYS if k not in self.m]
        self.assertEqual(missing, [], msg=f"Missing manifest keys: {missing}")

    def test_n_checks(self):
        self.assertGreaterEqual(self.m["n_checks"], 10,
                                msg=f"manifest n_checks should be ≥10, got {self.m['n_checks']}")

    def test_baseline_beta_positive(self):
        beta = self.m["baseline_beta_k0"]
        self.assertGreater(beta, 0, msg=f"manifest baseline_beta_k0 = {beta:.4f} should be positive")

    def test_covid_beta_positive(self):
        beta = self.m["covid_beta_k0"]
        self.assertGreater(beta, 0, msg=f"manifest covid_beta_k0 = {beta:.4f} should be positive")

    def test_placebo_beta_not_positive(self):
        beta = self.m["placebo_beta_k0"]
        self.assertLess(beta, 0.15,
                        msg=f"manifest placebo_beta_k0 = {beta:.4f} should not be meaningful")

    def test_n_obs_baseline(self):
        n = self.m["n_obs_baseline"]
        self.assertGreater(n, 2000, msg=f"manifest n_obs_baseline should be >2000, got {n}")

    def test_n_obs_covid_excl_reduced(self):
        n_base  = self.m["n_obs_baseline"]
        n_covid = self.m["n_obs_covid_excl"]
        self.assertLess(n_covid, n_base,
                        msg="COVID excl obs should be fewer than baseline")
        reduction = n_base - n_covid
        self.assertGreater(reduction, 100, msg=f"COVID reduction={reduction} too small")

    def test_theta_k0_by_check_populated(self):
        th = self.m["theta_k0_by_check"]
        self.assertIsInstance(th, dict, msg="theta_k0_by_check should be a dict")
        self.assertGreater(len(th), 0, msg="theta_k0_by_check should not be empty")

    def test_theta_k0_emfi_checks_positive(self):
        th = self.m["theta_k0_by_check"]
        for check_id in ["R03", "R04", "R05"]:
            if check_id in th:
                self.assertGreater(th[check_id], 0,
                                   msg=f"theta_k0_by_check[{check_id}] should be positive, got {th[check_id]:.4f}")

    def test_outputs_list(self):
        outputs = self.m.get("outputs", [])
        for fname in ["robustness_summary.csv", "manifest.json", "state_lp_theta.csv"]:
            self.assertIn(fname, outputs, msg=f"'{fname}' not in manifest outputs")

    def test_script_field(self):
        self.assertIn("robustness", self.m.get("script", ""),
                      msg="manifest script should reference robustness")

    def test_generated_at_format(self):
        import re
        ga = self.m.get("generated_at", "")
        self.assertRegex(ga, r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}",
                         msg=f"generated_at '{ga}' not ISO 8601")


# ===========================================================================
# 13. Figures
# ===========================================================================
class TestFigures(unittest.TestCase):
    FIGS = ["Fig_Robustness_LP.png", "Fig_Robustness_StateLPTheta.png"]
    MIN_SIZE = 20_000  # 20 KB
    PNG_HEADER = b"\x89PNG\r\n\x1a\n"

    def test_figures_minimum_size(self):
        for fig in self.FIGS:
            path = _path(fig)
            if not os.path.isfile(path):
                self.fail(f"Figure not found: {fig}")
            size = os.path.getsize(path)
            self.assertGreater(size, self.MIN_SIZE,
                               msg=f"{fig} is only {size} bytes (expected >{self.MIN_SIZE})")

    def test_figures_png_magic_bytes(self):
        for fig in self.FIGS:
            path = _path(fig)
            if not os.path.isfile(path):
                self.fail(f"Figure not found: {fig}")
            with open(path, "rb") as fh:
                header = fh.read(8)
            self.assertEqual(header, self.PNG_HEADER,
                             msg=f"{fig} does not start with PNG magic bytes")


if __name__ == "__main__":
    unittest.main(verbosity=2)
