"""
test_classify_events.py
=======================
Test suite for subprojects/08_event_classification/classify_events.py

Run from the Paper_GFJ directory:
    python -m pytest subprojects/08_event_classification/test_classify_events.py -v

Expected: all tests pass (outputs generated by classify_events.py).
"""

import json
import os
import unittest
from datetime import date

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
RESULTS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "results", "event_classification"
)


def _path(filename: str) -> str:
    return os.path.join(RESULTS_DIR, filename)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _load_taxonomy() -> pd.DataFrame:
    df = pd.read_csv(_path("event_taxonomy.csv"), parse_dates=["date"])
    df["date"] = pd.to_datetime(df["date"]).dt.date
    return df


def _load_summary() -> pd.DataFrame:
    return pd.read_csv(_path("summary_by_category.csv"))


def _load_market_stress() -> pd.DataFrame:
    df = pd.read_csv(_path("market_stress_episodes.csv"), parse_dates=["date"])
    df["date"] = pd.to_datetime(df["date"]).dt.date
    return df


def _load_manifest() -> dict:
    with open(_path("manifest.json")) as f:
        return json.load(f)


# ===========================================================================
# 1. Output file existence
# ===========================================================================
class TestOutputFiles(unittest.TestCase):
    """All expected output files must exist and be non-empty."""

    REQUIRED_FILES = [
        "event_taxonomy.csv",
        "summary_by_category.csv",
        "market_stress_episodes.csv",
        "manifest.json",
        "Fig_EventTimeline.png",
        "Fig_NetworkCorr_Systemic.png",
    ]

    def test_all_files_exist(self):
        missing = [f for f in self.REQUIRED_FILES if not os.path.isfile(_path(f))]
        self.assertEqual(missing, [], msg=f"Missing output files: {missing}")

    def test_all_files_nonempty(self):
        empty = [
            f for f in self.REQUIRED_FILES
            if os.path.isfile(_path(f)) and os.path.getsize(_path(f)) == 0
        ]
        self.assertEqual(empty, [], msg=f"Empty output files: {empty}")


# ===========================================================================
# 2. Taxonomy structure
# ===========================================================================
class TestTaxonomyStructure(unittest.TestCase):
    """event_taxonomy.csv must have the right shape and valid values."""

    REQUIRED_COLS = [
        "date", "max_shock", "breadth", "countries", "n_countries",
        "emfi_pre_mean", "emfi_post_mean", "emfi_post_max", "emfi_delta",
        "p_stress_on_day", "p_stress_peak", "tci_pre_mean", "tci_post_max",
        "category",
    ]

    @classmethod
    def setUpClass(cls):
        cls.df = _load_taxonomy()

    def test_row_count(self):
        self.assertEqual(len(self.df), 154,
                         msg="event_taxonomy.csv should have 154 shock-day rows")

    def test_required_columns(self):
        missing = [c for c in self.REQUIRED_COLS if c not in self.df.columns]
        self.assertEqual(missing, [], msg=f"Missing columns: {missing}")

    def test_category_values(self):
        valid = {"Absorbed", "Localized", "Systemic"}
        bad = set(self.df["category"].unique()) - valid
        self.assertEqual(bad, set(), msg=f"Unexpected category values: {bad}")

    def test_no_nan_in_key_cols(self):
        key_cols = ["date", "category", "emfi_post_max", "p_stress_peak", "emfi_delta"]
        for col in key_cols:
            n_nan = self.df[col].isna().sum()
            self.assertEqual(n_nan, 0, msg=f"NaN found in column '{col}': {n_nan} rows")

    def test_max_shock_positive(self):
        self.assertTrue((self.df["max_shock"] >= 0).all(),
                        msg="max_shock should be non-negative for all shock days")

    def test_p_stress_range(self):
        self.assertTrue((self.df["p_stress_peak"] >= 0).all() and
                        (self.df["p_stress_peak"] <= 1).all(),
                        msg="p_stress_peak must be in [0, 1]")

    def test_p_stress_on_day_range(self):
        self.assertTrue((self.df["p_stress_on_day"] >= 0).all() and
                        (self.df["p_stress_on_day"] <= 1).all(),
                        msg="p_stress_on_day must be in [0, 1]")

    def test_breadth_positive(self):
        self.assertTrue((self.df["breadth"] >= 1).all(),
                        msg="breadth (number of affected countries) should be >= 1")

    def test_n_countries_positive(self):
        self.assertTrue((self.df["n_countries"] >= 1).all(),
                        msg="n_countries should be >= 1")

    def test_dates_unique(self):
        dupes = self.df["date"].duplicated().sum()
        self.assertEqual(dupes, 0,
                         msg=f"event_taxonomy has {dupes} duplicate shock dates")

    def test_dates_sorted(self):
        dates = list(self.df["date"])
        self.assertEqual(dates, sorted(dates), msg="event_taxonomy dates should be sorted ascending")


# ===========================================================================
# 3. Category distribution
# ===========================================================================
class TestCategoryDistribution(unittest.TestCase):
    """Exact category counts must match verified results."""

    @classmethod
    def setUpClass(cls):
        cls.df = _load_taxonomy()
        cls.counts = cls.df["category"].value_counts().to_dict()

    def test_absorbed_count(self):
        self.assertEqual(self.counts.get("Absorbed", 0), 78,
                         msg=f"Expected 78 Absorbed, got {self.counts.get('Absorbed', 0)}")

    def test_systemic_count(self):
        self.assertEqual(self.counts.get("Systemic", 0), 42,
                         msg=f"Expected 42 Systemic, got {self.counts.get('Systemic', 0)}")

    def test_localized_count(self):
        self.assertEqual(self.counts.get("Localized", 0), 34,
                         msg=f"Expected 34 Localized, got {self.counts.get('Localized', 0)}")

    def test_total_adds_up(self):
        total = sum(self.counts.values())
        self.assertEqual(total, 154, msg=f"Category counts sum to {total}, expected 154")


# ===========================================================================
# 4. Systemic classification constraints
# ===========================================================================
class TestSystemicConstraints(unittest.TestCase):
    """Every Systemic event must satisfy both threshold criteria."""

    EMFI_Q75 = 0.548
    P_STRESS_THRESH = 0.50

    @classmethod
    def setUpClass(cls):
        df = _load_taxonomy()
        cls.systemic = df[df["category"] == "Systemic"].copy()

    def test_systemic_p_stress_peak_gte_threshold(self):
        failing = self.systemic[self.systemic["p_stress_peak"] < self.P_STRESS_THRESH]
        self.assertEqual(len(failing), 0,
                         msg=f"{len(failing)} Systemic events have p_stress_peak < {self.P_STRESS_THRESH}:\n{failing[['date','p_stress_peak']]}")

    def test_systemic_emfi_post_max_gte_q75(self):
        failing = self.systemic[self.systemic["emfi_post_max"] <= self.EMFI_Q75]
        self.assertEqual(len(failing), 0,
                         msg=f"{len(failing)} Systemic events have emfi_post_max <= {self.EMFI_Q75}:\n{failing[['date','emfi_post_max']]}")

    def test_systemic_mean_emfi_delta_positive(self):
        mean_delta = self.systemic["emfi_delta"].mean()
        self.assertGreater(mean_delta, 0,
                           msg=f"Mean emfi_delta for Systemic events should be positive, got {mean_delta:.4f}")


# ===========================================================================
# 5. Localized classification constraints
# ===========================================================================
class TestLocalizedConstraints(unittest.TestCase):
    """Localized events: EMFI improves but P_stress doesn't breach threshold at peak."""

    P_STRESS_THRESH = 0.50

    @classmethod
    def setUpClass(cls):
        df = _load_taxonomy()
        cls.localized = df[df["category"] == "Localized"].copy()

    def test_localized_not_systemic(self):
        """Localized events should not meet both systemic criteria simultaneously."""
        EMFI_Q75 = 0.548
        both = self.localized[
            (self.localized["p_stress_peak"] >= self.P_STRESS_THRESH) &
            (self.localized["emfi_post_max"] > EMFI_Q75)
        ]
        self.assertEqual(len(both), 0,
                         msg=f"{len(both)} Localized events meet both Systemic criteria (should be 0)")

    def test_localized_mean_emfi_delta_positive(self):
        mean_delta = self.localized["emfi_delta"].mean()
        self.assertGreater(mean_delta, 0,
                           msg=f"Localized mean emfi_delta should be positive (EMFI rises), got {mean_delta:.4f}")


# ===========================================================================
# 6. Absorbed classification constraints
# ===========================================================================
class TestAbsorbedConstraints(unittest.TestCase):
    """Absorbed events: EMFI falls or stays flat on average."""

    @classmethod
    def setUpClass(cls):
        df = _load_taxonomy()
        cls.absorbed = df[df["category"] == "Absorbed"].copy()

    def test_absorbed_mean_emfi_delta_negative(self):
        mean_delta = self.absorbed["emfi_delta"].mean()
        self.assertLess(mean_delta, 0,
                        msg=f"Absorbed mean emfi_delta should be negative (shock absorbed), got {mean_delta:.4f}")

    def test_absorbed_low_p_stress(self):
        """Absorbed events should have low average P_stress_peak."""
        mean_p = self.absorbed["p_stress_peak"].mean()
        self.assertLess(mean_p, 0.20,
                        msg=f"Absorbed events should have mean p_stress_peak < 0.20, got {mean_p:.4f}")


# ===========================================================================
# 7. Anchor event classifications
# ===========================================================================
class TestAnchorEvents(unittest.TestCase):
    """Key geopolitical events must be classified as expected."""

    @classmethod
    def setUpClass(cls):
        cls.df = _load_taxonomy()
        cls.df_indexed = cls.df.set_index("date")

    def _get_row(self, dt: date):
        if dt in self.df_indexed.index:
            return self.df_indexed.loc[dt]
        return None

    def test_covid_march_2020_systemic(self):
        row = self._get_row(date(2020, 3, 3))
        self.assertIsNotNone(row, msg="2020-03-03 (COVID shock) not found in taxonomy")
        self.assertEqual(row["category"], "Systemic",
                         msg=f"COVID shock 2020-03-03 should be Systemic, got {row['category']}")

    def test_covid_emfi_post_max(self):
        row = self._get_row(date(2020, 3, 3))
        self.assertIsNotNone(row, msg="2020-03-03 not found")
        self.assertGreater(row["emfi_post_max"], 10.0,
                           msg=f"COVID shock should have emfi_post_max > 10, got {row['emfi_post_max']:.4f}")

    def test_ukraine_feb_2022_systemic(self):
        row = self._get_row(date(2022, 2, 24))
        self.assertIsNotNone(row, msg="2022-02-24 (Ukraine invasion) not found in taxonomy")
        self.assertEqual(row["category"], "Systemic",
                         msg=f"Ukraine invasion 2022-02-24 should be Systemic, got {row['category']}")

    def test_ukraine_emfi_post_max(self):
        row = self._get_row(date(2022, 2, 24))
        self.assertIsNotNone(row, msg="2022-02-24 not found")
        self.assertGreater(row["emfi_post_max"], 5.0,
                           msg=f"Ukraine invasion should have emfi_post_max > 5, got {row['emfi_post_max']:.4f}")

    def test_hamas_oct_2023_systemic(self):
        """Hamas attack 2023-10-09: classified Systemic due to P_stress spike on 2023-10-10."""
        row = self._get_row(date(2023, 10, 9))
        self.assertIsNotNone(row, msg="2023-10-09 (Hamas attack) not found in taxonomy")
        self.assertEqual(row["category"], "Systemic",
                         msg=f"Hamas 2023-10-09 should be Systemic (P_stress spike next day), got {row['category']}")

    def test_covid_highest_emfi_post_max(self):
        """COVID March 2020 should have the highest emfi_post_max of any event."""
        df = _load_taxonomy()
        max_row = df.loc[df["emfi_post_max"].idxmax()]
        self.assertEqual(max_row["date"], date(2020, 3, 3),
                         msg=f"Highest emfi_post_max expected on 2020-03-03, got {max_row['date']}")


# ===========================================================================
# 8. Summary CSV
# ===========================================================================
class TestSummaryCSV(unittest.TestCase):
    """summary_by_category.csv must have correct structure and values."""

    @classmethod
    def setUpClass(cls):
        cls.df = _load_summary()

    def test_three_categories(self):
        self.assertEqual(len(self.df), 3,
                         msg=f"summary_by_category should have 3 rows, got {len(self.df)}")

    def test_required_columns(self):
        required = ["category", "n_events", "pct_events"]
        missing = [c for c in required if c not in self.df.columns]
        self.assertEqual(missing, [], msg=f"Missing columns in summary: {missing}")

    def test_pct_events_sums_to_100(self):
        total = self.df["pct_events"].sum()
        self.assertAlmostEqual(total, 100.0, places=1,
                               msg=f"pct_events should sum to 100, got {total:.2f}")

    def test_n_events_sum(self):
        total = self.df["n_events"].sum()
        self.assertEqual(total, 154, msg=f"n_events should sum to 154, got {total}")

    def test_systemic_n_events(self):
        systemic_row = self.df[self.df["category"] == "Systemic"]
        self.assertFalse(systemic_row.empty, msg="'Systemic' row missing from summary")
        n = int(systemic_row["n_events"].iloc[0])
        self.assertEqual(n, 42, msg=f"Systemic n_events should be 42, got {n}")

    def test_localized_n_events(self):
        row = self.df[self.df["category"] == "Localized"]
        self.assertFalse(row.empty, msg="'Localized' row missing from summary")
        n = int(row["n_events"].iloc[0])
        self.assertEqual(n, 34, msg=f"Localized n_events should be 34, got {n}")

    def test_absorbed_n_events(self):
        row = self.df[self.df["category"] == "Absorbed"]
        self.assertFalse(row.empty, msg="'Absorbed' row missing from summary")
        n = int(row["n_events"].iloc[0])
        self.assertEqual(n, 78, msg=f"Absorbed n_events should be 78, got {n}")

    def test_mean_p_stress_ordering(self):
        """Systemic should have highest mean p_stress_peak, Absorbed lowest."""
        if "mean_p_stress_peak" not in self.df.columns:
            self.skipTest("mean_p_stress_peak column not in summary — skipping ordering check")
        d = self.df.set_index("category")["mean_p_stress_peak"]
        self.assertGreater(d["Systemic"], d["Localized"],
                           msg="Systemic should have higher mean p_stress_peak than Localized")
        self.assertGreater(d["Localized"], d["Absorbed"],
                           msg="Localized should have higher mean p_stress_peak than Absorbed")


# ===========================================================================
# 9. Market-only stress episodes
# ===========================================================================
class TestMarketStressEpisodes(unittest.TestCase):
    """market_stress_episodes.csv: 138 days, all with P_stress > 0.5."""

    @classmethod
    def setUpClass(cls):
        cls.df = _load_market_stress()

    def test_row_count(self):
        self.assertEqual(len(self.df), 138,
                         msg=f"market_stress_episodes should have 138 rows, got {len(self.df)}")

    def test_required_columns(self):
        for col in ["date", "P_stress"]:
            self.assertIn(col, self.df.columns, msg=f"Missing column '{col}' in market_stress_episodes")

    def test_p_stress_above_threshold(self):
        below = self.df[self.df["P_stress"] <= 0.5]
        self.assertEqual(len(below), 0,
                         msg=f"{len(below)} market-stress days have P_stress <= 0.5 (should be 0)")

    def test_dates_unique(self):
        dupes = self.df["date"].duplicated().sum()
        self.assertEqual(dupes, 0,
                         msg=f"market_stress_episodes has {dupes} duplicate dates")

    def test_dates_sorted(self):
        dates = list(self.df["date"])
        self.assertEqual(dates, sorted(dates),
                         msg="market_stress_episodes dates should be sorted ascending")


# ===========================================================================
# 10. Manifest
# ===========================================================================
class TestManifest(unittest.TestCase):
    """manifest.json must have correct keys and values."""

    REQUIRED_KEYS = [
        "generated_at", "script", "n_shock_days", "emfi_q75",
        "p_stress_threshold", "category_counts", "market_only_stress_days",
        "top_systemic_events", "outputs",
    ]

    @classmethod
    def setUpClass(cls):
        cls.m = _load_manifest()

    def test_required_keys(self):
        missing = [k for k in self.REQUIRED_KEYS if k not in self.m]
        self.assertEqual(missing, [], msg=f"Missing manifest keys: {missing}")

    def test_n_shock_days(self):
        self.assertEqual(self.m["n_shock_days"], 154,
                         msg=f"manifest n_shock_days should be 154, got {self.m['n_shock_days']}")

    def test_emfi_q75(self):
        self.assertAlmostEqual(self.m["emfi_q75"], 0.548, places=2,
                               msg=f"manifest emfi_q75 should be ~0.548, got {self.m['emfi_q75']}")

    def test_p_stress_threshold(self):
        self.assertAlmostEqual(self.m["p_stress_threshold"], 0.5, places=2,
                               msg=f"manifest p_stress_threshold should be 0.5, got {self.m['p_stress_threshold']}")

    def test_category_counts_keys(self):
        cc = self.m.get("category_counts", {})
        for cat in ["Absorbed", "Systemic", "Localized"]:
            self.assertIn(cat, cc, msg=f"category_counts missing key '{cat}'")

    def test_category_counts_values(self):
        cc = self.m["category_counts"]
        self.assertEqual(cc["Absorbed"], 78, msg=f"category_counts Absorbed should be 78, got {cc['Absorbed']}")
        self.assertEqual(cc["Systemic"], 42, msg=f"category_counts Systemic should be 42, got {cc['Systemic']}")
        self.assertEqual(cc["Localized"], 34, msg=f"category_counts Localized should be 34, got {cc['Localized']}")

    def test_market_only_stress_days(self):
        self.assertEqual(self.m["market_only_stress_days"], 138,
                         msg=f"manifest market_only_stress_days should be 138, got {self.m['market_only_stress_days']}")

    def test_top_systemic_events_nonempty(self):
        top = self.m.get("top_systemic_events", [])
        self.assertGreater(len(top), 0, msg="top_systemic_events list should not be empty")

    def test_top_systemic_event_fields(self):
        top = self.m.get("top_systemic_events", [])
        if not top:
            self.skipTest("top_systemic_events is empty")
        required = {"date", "p_stress_peak", "emfi_post_max", "countries"}
        for i, ev in enumerate(top):
            missing = required - set(ev.keys())
            self.assertEqual(missing, set(), msg=f"top_systemic_events[{i}] missing fields: {missing}")

    def test_outputs_list(self):
        outputs = self.m.get("outputs", [])
        self.assertGreater(len(outputs), 0, msg="manifest outputs list should not be empty")
        for fname in ["event_taxonomy.csv", "summary_by_category.csv", "manifest.json"]:
            self.assertIn(fname, outputs, msg=f"'{fname}' not listed in manifest outputs")

    def test_generated_at_format(self):
        import re
        ga = self.m.get("generated_at", "")
        # ISO 8601 format with T separator and timezone
        self.assertRegex(ga, r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}",
                         msg=f"generated_at '{ga}' doesn't look like ISO 8601")

    def test_script_field(self):
        script = self.m.get("script", "")
        self.assertIn("classify_events", script,
                      msg=f"manifest script field should reference classify_events, got '{script}'")


# ===========================================================================
# 11. Year distribution
# ===========================================================================
class TestYearDistribution(unittest.TestCase):
    """Cross-checks on year-level patterns known from the data."""

    @classmethod
    def setUpClass(cls):
        df = _load_taxonomy()
        df["year"] = pd.to_datetime(df["date"]).dt.year
        cls.df = df
        cls.by_year = df.groupby("year")["category"].value_counts().unstack(fill_value=0)

    def test_2022_highest_systemic_count(self):
        """2022 (Ukraine + energy crisis) should have the most Systemic events."""
        if "Systemic" not in self.by_year.columns:
            self.skipTest("No Systemic column in year breakdown")
        max_year = self.by_year["Systemic"].idxmax()
        self.assertEqual(max_year, 2022,
                         msg=f"2022 should have the most Systemic events, got {max_year}")

    def test_2020_significant_systemic(self):
        """2020 should have at least 5 Systemic events (COVID cluster)."""
        if "Systemic" not in self.by_year.columns:
            self.skipTest("No Systemic column in year breakdown")
        n_2020 = self.by_year["Systemic"].get(2020, 0)
        self.assertGreaterEqual(n_2020, 5,
                                msg=f"2020 should have >= 5 Systemic events, got {n_2020}")

    def test_sample_covers_multiple_years(self):
        years = pd.to_datetime(self.df["date"]).dt.year.unique()
        self.assertGreaterEqual(len(years), 5,
                                msg=f"Taxonomy should span at least 5 years, got {len(years)}")


# ===========================================================================
# 12. Figures
# ===========================================================================
class TestFigures(unittest.TestCase):
    """PNG figures must be real image files with non-trivial size."""

    FIGS = ["Fig_EventTimeline.png", "Fig_NetworkCorr_Systemic.png"]
    MIN_SIZE_BYTES = 10_000  # at least 10 KB

    def test_figures_minimum_size(self):
        for fig in self.FIGS:
            path = _path(fig)
            if not os.path.isfile(path):
                self.fail(f"Figure not found: {fig}")
            size = os.path.getsize(path)
            self.assertGreater(size, self.MIN_SIZE_BYTES,
                               msg=f"{fig} is only {size} bytes — may be empty/corrupt")

    def test_figures_png_magic_bytes(self):
        PNG_HEADER = b"\x89PNG\r\n\x1a\n"
        for fig in self.FIGS:
            path = _path(fig)
            if not os.path.isfile(path):
                self.fail(f"Figure not found: {fig}")
            with open(path, "rb") as fh:
                header = fh.read(8)
            self.assertEqual(header, PNG_HEADER,
                             msg=f"{fig} does not start with PNG magic bytes")


if __name__ == "__main__":
    unittest.main(verbosity=2)
